// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertiesMinimalAPI.Data;

#nullable disable

namespace PropertiesMinimalAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241217205143_CreationProperties")]
    partial class CreationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertiesMinimalAPI.Models.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8662),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test1",
                            Name = "Casa las palmas 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8666),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test2",
                            Name = "Casa las palmas 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8668),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test3",
                            Name = "Casa las palmas 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8669),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test4",
                            Name = "Casa las palmas 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8670),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test5",
                            Name = "Casa las palmas 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 17, 20, 51, 43, 417, DateTimeKind.Utc).AddTicks(8671),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Test6",
                            Name = "Casa las palmas 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
